import { Suspense } from 'react';
import AdminLayout from '@/components/AdminLayout';
import RoomPageSkeleton from './components/RoomPageSkeleton';
import RoomClientView from './components/RoomClientView'; // We will create this next

const fetchRoomData = async () => {
    const initialRoomsData = {
        A1: { id: "A1", name: "Room A1", building: "Building A", floor: 5, capacity: 30, equipment: ["Projector", "Whiteboard", "AC"] },
        A2: { id: "A2", name: "Room A2", building: "Building A", floor: 5, capacity: 20, equipment: ["Whiteboard", "AC"] },
        A3: { id: "A3", name: "Room A3", building: "Building A", floor: 5, capacity: 25, equipment: ["Projector", "AC"] },
        A4: { id: "A4", name: "Room A4", building: "Building A", floor: 5, capacity: 18, equipment: ["Whiteboard"] },
        A5: { id: "A5", name: "Room A5", building: "Building A", floor: 5, capacity: 22, equipment: ["Projector", "AC"] },
        A6: { id: "A6", name: "Room A6", building: "Building A", floor: 5, capacity: 18, equipment: ["Whiteboard"] },
        A7: { id: "A7", name: "Room A7", building: "Building A", floor: 5, capacity: 20, equipment: ["Projector", "AC"] },
        A8: { id: "A8", name: "Room A8", building: "Building A", floor: 5, capacity: 16, equipment: ["Whiteboard"] },
        A9: { id: "A9", name: "Room A9", building: "Building A", floor: 5, capacity: 18, equipment: ["Projector", "AC"] },
        A10: { id: "A10", name: "Room A10", building: "Building A", floor: 5, capacity: 20, equipment: ["Whiteboard"] },
        A11: { id: "A11", name: "Room A11", building: "Building A", floor: 5, capacity: 22, equipment: ["Projector", "AC"] },
        A12: { id: "A12", name: "Room A12", building: "Building A", floor: 5, capacity: 18, equipment: ["Whiteboard"] },
        A13: { id: "A13", name: "Room A13", building: "Building A", floor: 5, capacity: 20, equipment: ["Projector", "AC"] },
        A14: { id: "A14", name: "Room A14", building: "Building A", floor: 5, capacity: 16, equipment: ["Whiteboard"] },
        A15: { id: "A15", name: "Room A15", building: "Building A", floor: 5, capacity: 18, equipment: ["Projector", "AC"] },
        A16: { id: "A16", name: "Room A16", building: "Building A", floor: 5, capacity: 20, equipment: ["Whiteboard"] },
        A17: { id: "A17", name: "Room A17", building: "Building A", floor: 5, capacity: 22, equipment: ["Projector", "AC"] },
        A18: { id: "A18", name: "Room A18", building: "Building A", floor: 5, capacity: 18, equipment: ["Whiteboard"] },
        A19: { id: "A19", name: "Room A19", building: "Building A", floor: 5, capacity: 20, equipment: ["Projector", "AC"] },
        A20: { id: "A20", name: "Room A20", building: "Building A", floor: 5, capacity: 16, equipment: ["Whiteboard"] },
        A21: { id: "A21", name: "Room A21", building: "Building A", floor: 5, capacity: 18, equipment: ["Projector", "AC"] },
        A22: { id: "A22", name: "Room A22", building: "Building A", floor: 5, capacity: 20, equipment: ["Whiteboard"] },
        A23: { id: "A23", name: "Room A23", building: "Building A", floor: 5, capacity: 22, equipment: ["Projector", "AC"] },
        A24: { id: "A24", name: "Room A24", building: "Building A", floor: 5, capacity: 18, equipment: ["Whiteboard"] },
        A25: { id: "A25", name: "Room A25", building: "Building A", floor: 5, capacity: 20, equipment: ["Projector", "AC"] },
        B1: { id: "B1", name: "Room B1", building: "Building A", floor: 4, capacity: 15, equipment: ["Projector", "AC"] },
        B2: { id: "B2", name: "Room B2", building: "Building A", floor: 4, capacity: 20, equipment: ["Whiteboard"] },
        B3: { id: "B3", name: "Room B3", building: "Building A", floor: 4, capacity: 18, equipment: ["Projector", "AC"] },
        B4: { id: "B4", name: "Room B4", building: "Building A", floor: 4, capacity: 22, equipment: ["Whiteboard"] },
        B5: { id: "B5", name: "Room B5", building: "Building A", floor: 4, capacity: 20, equipment: ["Projector", "AC"] },
        B6: { id: "B6", name: "Room B6", building: "Building A", floor: 4, capacity: 18, equipment: ["Whiteboard"] },
        B7: { id: "B7", name: "Room B7", building: "Building A", floor: 4, capacity: 22, equipment: ["Projector", "AC"] },
        B8: { id: "B8", name: "Room B8", building: "Building A", floor: 4, capacity: 20, equipment: ["Whiteboard"] },
        B9: { id: "B9", name: "Room B9", building: "Building A", floor: 4, capacity: 18, equipment: ["Projector", "AC"] },
        B10: { id: "B10", name: "Room B10", building: "Building A", floor: 4, capacity: 22, equipment: ["Whiteboard"] },
        B11: { id: "B11", name: "Room B11", building: "Building A", floor: 4, capacity: 20, equipment: ["Projector", "AC"] },
        B12: { id: "B12", name: "Room B12", building: "Building A", floor: 4, capacity: 18, equipment: ["Whiteboard"] },
        B13: { id: "B13", name: "Room B13", building: "Building A", floor: 4, capacity: 22, equipment: ["Projector", "AC"] },
        B14: { id: "B14", name: "Room B14", building: "Building A", floor: 4, capacity: 20, equipment: ["Whiteboard"] },
        B15: { id: "B15", name: "Room B15", building: "Building A", floor: 4, capacity: 18, equipment: ["Projector", "AC"] },
        B16: { id: "B16", name: "Room B16", building: "Building A", floor: 4, capacity: 22, equipment: ["Whiteboard"] },
        B17: { id: "B17", name: "Room B17", building: "Building A", floor: 4, capacity: 20, equipment: ["Projector", "AC"] },
        B18: { id: "B18", name: "Room B18", building: "Building A", floor: 4, capacity: 18, equipment: ["Whiteboard"] },
        B19: { id: "B19", name: "Room B19", building: "Building A", floor: 4, capacity: 22, equipment: ["Projector", "AC"] },
        B20: { id: "B20", name: "Room B20", building: "Building A", floor: 4, capacity: 20, equipment: ["Whiteboard"] },
        B21: { id: "B21", name: "Room B21", building: "Building A", floor: 4, capacity: 18, equipment: ["Projector", "AC"] },
        B22: { id: "B22", name: "Room B22", building: "Building A", floor: 4, capacity: 22, equipment: ["Whiteboard"] },
        B23: { id: "B23", name: "Room B23", building: "Building A", floor: 4, capacity: 20, equipment: ["Projector", "AC"] },
        B24: { id: "B24", name: "Room B24", building: "Building A", floor: 4, capacity: 18, equipment: ["Whiteboard"] },
        B25: { id: "B25", name: "Room B25", building: "Building A", floor: 4, capacity: 22, equipment: ["Projector", "AC"] },
        C1: { id: "C1", name: "Room C1", building: "Building A", floor: 3, capacity: 10, equipment: ["AC"] },
        C2: { id: "C2", name: "Room C2", building: "Building A", floor: 3, capacity: 12, equipment: ["Whiteboard", "AC"] },
        C3: { id: "C3", name: "Room C3", building: "Building A", floor: 2, capacity: 8, equipment: ["Projector"] },
        C4: { id: "C4", name: "Room C4", building: "Building A", floor: 2, capacity: 10, equipment: ["Whiteboard"] },
        C5: { id: "C5", name: "Room C5", building: "Building A", floor: 1, capacity: 5, equipment: ["AC"] },
        C6: { id: "C6", name: "Room C6", building: "Building A", floor: 1, capacity: 6, equipment: ["Projector", "Whiteboard"] },
        C7: { id: "C7", name: "Room C7", building: "Building B", floor: 3, capacity: 12, equipment: ["Projector", "Whiteboard"] },
        C8: { id: "C8", name: "Room C8", building: "Building B", floor: 3, capacity: 10, equipment: ["AC"] },
        C9: { id: "C9", name: "Room C9", building: "Building B", floor: 2, capacity: 8, equipment: ["Whiteboard"] },
        C10: { id: "C10", name: "Room C10", building: "Building B", floor: 2, capacity: 6, equipment: ["Projector"] },
        C11: { id: "C11", name: "Room C11", building: "Building B", floor: 1, capacity: 5, equipment: ["AC"] },
        C12: { id: "C12", name: "Room C12", building: "Building B", floor: 1, capacity: 4, equipment: ["Whiteboard"] },
        C13: { id: "C13", name: "Room C13", building: "Building C", floor: 3, capacity: 15, equipment: ["Projector", "AC"] },
        C14: { id: "C14", name: "Room C14", building: "Building C", floor: 3, capacity: 9, equipment: ["Whiteboard"] },
        C15: { id: "C15", name: "Room C15", building: "Building C", floor: 2, capacity: 7, equipment: ["AC", "Whiteboard"] },
        C16: { id: "C16", name: "Room C16", building: "Building C", floor: 2, capacity: 11, equipment: ["Projector"] },
        C17: { id: "C17", name: "Room C17", building: "Building C", floor: 1, capacity: 6, equipment: ["AC"] },
        C18: { id: "C18", name: "Room C18", building: "Building C", floor: 1, capacity: 8, equipment: ["Whiteboard"] },
        C19: { id: "C19", name: "Room C19", building: "Building D", floor: 4, capacity: 13, equipment: ["Projector", "AC", "Whiteboard"] },
        C20: { id: "C20", name: "Room C20", building: "Building D", floor: 4, capacity: 10, equipment: ["AC"] },
        C21: { id: "C21", name: "Room C21", building: "Building D", floor: 3, capacity: 9, equipment: ["Whiteboard"] },
        C22: { id: "C22", name: "Room C22", building: "Building D", floor: 3, capacity: 7, equipment: ["Projector"] },
        C23: { id: "C23", name: "Room C23", building: "Building D", floor: 2, capacity: 6, equipment: ["AC"] },
        C24: { id: "C24", name: "Room C24", building: "Building D", floor: 2, capacity: 8, equipment: ["Whiteboard"] },
        C25: { id: "C25", name: "Room C25", building: "Building D", floor: 1, capacity: 5, equipment: ["Projector"] },
        D1: { id: "D1", name: "Room D1", building: "Building A", floor: 1, capacity: 7, equipment: ["Whiteboard", "AC"] },
        D2: { id: "D2", name: "Room D2", building: "Building A", floor: 1, capacity: 9, equipment: ["Projector"] },
        D3: { id: "D3", name: "Room D3", building: "Building A", floor: 2, capacity: 11, equipment: ["AC"] },
        D4: { id: "D4", name: "Room D4", building: "Building A", floor: 2, capacity: 8, equipment: ["Whiteboard"] },
        D5: { id: "D5", name: "Room D5", building: "Building A", floor: 3, capacity: 13, equipment: ["Projector", "Whiteboard"] },
        D6: { id: "D6", name: "Room D6", building: "Building A", floor: 3, capacity: 6, equipment: ["AC"] },
        D7: { id: "D7", name: "Room D7", building: "Building B", floor: 1, capacity: 5, equipment: ["Whiteboard"] },
        D8: { id: "D8", name: "Room D8", building: "Building B", floor: 1, capacity: 7, equipment: ["Projector"] },
        D9: { id: "D9", name: "Room D9", building: "Building B", floor: 2, capacity: 10, equipment: ["AC", "Whiteboard"] },
        D10: { id: "D10", name: "Room D10", building: "Building B", floor: 2, capacity: 12, equipment: ["Whiteboard"] },
        D11: { id: "D11", name: "Room D11", building: "Building B", floor: 3, capacity: 14, equipment: ["Projector", "AC"] },
        D12: { id: "D12", name: "Room D12", building: "Building B", floor: 3, capacity: 8, equipment: ["AC"] },
        D13: { id: "D13", name: "Room D13", building: "Building C", floor: 1, capacity: 6, equipment: ["Whiteboard"] },
        D14: { id: "D14", name: "Room D14", building: "Building C", floor: 1, capacity: 9, equipment: ["Projector"] },
        D15: { id: "D15", name: "Room D15", building: "Building C", floor: 2, capacity: 11, equipment: ["AC"] },
        D16: { id: "D16", name: "Room D16", building: "Building C", floor: 2, capacity: 7, equipment: ["Whiteboard", "AC"] },
        D17: { id: "D17", name: "Room D17", building: "Building C", floor: 3, capacity: 15, equipment: ["Projector"] },
        D18: { id: "D18", name: "Room D18", building: "Building C", floor: 3, capacity: 10, equipment: ["AC"] },
        D19: { id: "D19", name: "Room D19", building: "Building D", floor: 1, capacity: 5, equipment: ["Whiteboard"] },
        D20: { id: "D20", name: "Room D20", building: "Building D", floor: 1, capacity: 8, equipment: ["Projector"] },
        D21: { id: "D21", name: "Room D21", building: "Building D", floor: 2, capacity: 12, equipment: ["AC", "Whiteboard"] },
        D22: { id: "D22", name: "Room D22", building: "Building D", floor: 2, capacity: 9, equipment: ["Whiteboard"] },
        D23: { id: "D23", name: "Room D23", building: "Building D", floor: 3, capacity: 14, equipment: ["Projector"] },
        D24: { id: "D24", name: "Room D24", building: "Building D", floor: 3, capacity: 6, equipment: ["AC"] },
        D25: { id: "D25", name: "Room D25", building: "Building D", floor: 4, capacity: 10, equipment: ["Whiteboard", "AC"] },
        E1: { id: "E1", name: "Room E1", building: "Building A", floor: 1, capacity: 5, equipment: ["AC"] },
        E2: { id: "E2", name: "Room E2", building: "Building A", floor: 1, capacity: 6, equipment: ["Projector", "Whiteboard"] },
        E3: { id: "E3", name: "Room E3", building: "Building A", floor: 2, capacity: 8, equipment: ["Whiteboard"] },
        E4: { id: "E4", name: "Room E4", building: "Building A", floor: 2, capacity: 10, equipment: ["AC", "Projector"] },
        E5: { id: "E5", name: "Room E5", building: "Building A", floor: 3, capacity: 12, equipment: ["AC"] },
        E6: { id: "E6", name: "Room E6", building: "Building A", floor: 3, capacity: 9, equipment: ["Whiteboard", "Projector"] },
        E7: { id: "E7", name: "Room E7", building: "Building B", floor: 1, capacity: 7, equipment: ["Projector"] },
        E8: { id: "E8", name: "Room E8", building: "Building B", floor: 1, capacity: 11, equipment: ["AC"] },
        E9: { id: "E9", name: "Room E9", building: "Building B", floor: 2, capacity: 13, equipment: ["Whiteboard", "AC"] },
        E10: { id: "E10", name: "Room E10", building: "Building B", floor: 2, capacity: 15, equipment: ["Projector", "Whiteboard"] },
        E11: { id: "E11", name: "Room E11", building: "Building B", floor: 3, capacity: 6, equipment: ["AC"] },
        E12: { id: "E12", name: "Room E12", building: "Building B", floor: 3, capacity: 8, equipment: ["Whiteboard"] },
        E13: { id: "E13", name: "Room E13", building: "Building C", floor: 1, capacity: 5, equipment: ["Projector"] },
        E14: { id: "E14", name: "Room E14", building: "Building C", floor: 1, capacity: 9, equipment: ["AC"] },
        E15: { id: "E15", name: "Room E15", building: "Building C", floor: 2, capacity: 10, equipment: ["Whiteboard", "AC"] },
        E16: { id: "E16", name: "Room E16", building: "Building C", floor: 2, capacity: 7, equipment: ["Projector"] },
        E17: { id: "E17", name: "Room E17", building: "Building C", floor: 3, capacity: 14, equipment: ["AC", "Whiteboard"] },
        E18: { id: "E18", name: "Room E18", building: "Building C", floor: 3, capacity: 11, equipment: ["Projector"] },
        E19: { id: "E19", name: "Room E19", building: "Building D", floor: 1, capacity: 4, equipment: ["Whiteboard"] },
        E20: { id: "E20", name: "Room E20", building: "Building D", floor: 1, capacity: 6, equipment: ["AC"] },
        E21: { id: "E21", name: "Room E21", building: "Building D", floor: 2, capacity: 8, equipment: ["Projector", "Whiteboard"] },
        E22: { id: "E22", name: "Room E22", building: "Building D", floor: 2, capacity: 10, equipment: ["AC"] },
        E23: { id: "E23", name: "Room E23", building: "Building D", floor: 3, capacity: 12, equipment: ["Whiteboard"] },
        E24: { id: "E24", name: "Room E24", building: "Building D", floor: 3, capacity: 15, equipment: ["Projector", "AC"] },
        E25: { id: "E25", name: "Room E25", building: "Building D", floor: 4, capacity: 13, equipment: ["AC", "Whiteboard"] },
        F1: { id: "F1", name: "Room F1", building: "Building A", floor: 4, capacity: 12, equipment: ["Projector", "Whiteboard"] },
        F2: { id: "F2", name: "Room F2", building: "Building A", floor: 4, capacity: 10, equipment: ["AC"] },
        F3: { id: "F3", name: "Room F3", building: "Building A", floor: 3, capacity: 8, equipment: ["Whiteboard"] },
        F4: { id: "F4", name: "Room F4", building: "Building A", floor: 3, capacity: 6, equipment: ["Projector"] },
        F5: { id: "F5", name: "Room F5", building: "Building A", floor: 2, capacity: 5, equipment: ["AC"] },
        F6: { id: "F6", name: "Room F6", building: "Building A", floor: 2, capacity: 4, equipment: ["Whiteboard"] },
        F7: { id: "F7", name: "Room F7", building: "Building B", floor: 4, capacity: 15, equipment: ["Projector", "AC", "Whiteboard"] },
        F8: { id: "F8", name: "Room F8", building: "Building B", floor: 4, capacity: 7, equipment: ["AC"] },
        F9: { id: "F9", name: "Room F9", building: "Building B", floor: 3, capacity: 9, equipment: ["Whiteboard", "AC"] },
        F10: { id: "F10", name: "Room F10", building: "Building B", floor: 3, capacity: 11, equipment: ["Projector"] },
        F11: { id: "F11", name: "Room F11", building: "Building B", floor: 2, capacity: 6, equipment: ["AC"] },
        F12: { id: "F12", name: "Room F12", building: "Building B", floor: 2, capacity: 8, equipment: ["Whiteboard"] },
        F13: { id: "F13", name: "Room F13", building: "Building C", floor: 4, capacity: 10, equipment: ["Projector", "AC"] },
        F14: { id: "F14", name: "Room F14", building: "Building C", floor: 4, capacity: 7, equipment: ["Whiteboard"] },
        F15: { id: "F15", name: "Room F15", building: "Building C", floor: 3, capacity: 14, equipment: ["AC"] },
        F16: { id: "F16", name: "Room F16", building: "Building C", floor: 3, capacity: 9, equipment: ["Projector", "Whiteboard"] },
        F17: { id: "F17", name: "Room F17", building: "Building C", floor: 2, capacity: 5, equipment: ["AC"] },
        F18: { id: "F18", name: "Room F18", building: "Building C", floor: 2, capacity: 6, equipment: ["Whiteboard"] },
        F19: { id: "F19", name: "Room F19", building: "Building D", floor: 4, capacity: 11, equipment: ["Projector"] },
        F20: { id: "F20", name: "Room F20", building: "Building D", floor: 4, capacity: 13, equipment: ["AC", "Whiteboard"] },
        F21: { id: "F21", name: "Room F21", building: "Building D", floor: 3, capacity: 8, equipment: ["Whiteboard"] },
        F22: { id: "F22", name: "Room F22", building: "Building D", floor: 3, capacity: 9, equipment: ["Projector", "AC"] },
        F23: { id: "F23", name: "Room F23", building: "Building D", floor: 2, capacity: 7, equipment: ["AC"] },
        F24: { id: "F24", name: "Room F24", building: "Building D", floor: 2, capacity: 5, equipment: ["Whiteboard"] },
        F25: { id: "F25", name: "Room F25", building: "Building D", floor: 1, capacity: 10, equipment: ["Projector", "Whiteboard", "AC"] }
    };

    // Simulate network delay for fetching data
    await new Promise(resolve => setTimeout(resolve, 500));
    return initialRoomsData;
};

export default async function AdminRoomPage() {
    // Data is fetched on the server before the page is sent to the client.
    const allRoomsData = await fetchRoomData();

    return (
        <AdminLayout activeItem="room" pageTitle="Room Management">
            <Suspense fallback={<RoomPageSkeleton />}>
                {/* The Client Component is rendered here, receiving the server-fetched data as a prop.
                  The browser gets the pre-rendered HTML for the list of rooms, making the initial
                  load appear instant. Then, the client-side JavaScript will load to make it interactive.
                */}
                <RoomClientView initialAllRoomsData={allRoomsData} />
            </Suspense>
        </AdminLayout>
    );
}